# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
install:
    make build
script:
 - python -m unittest discover
notifications:
  email: 
    - apclary@gmail.com